version: "3.3"

services:
    tests:
        depends_on:
            - test-server
        container_name: tests
        build:
            context: .
            dockerfile: Dockerfile.test
    test-server:
        build:
            context: .
            dockerfile: Dockerfile.test.srv
        container_name: test_server
        restart: always
        expose:
            - "1337"
