version: "3.3"

services:
    tests:
        depends_on:
            - test-server
            - proxy
        container_name: tests
        build:
            context: .
            dockerfile: Dockerfile.test
    proxy:
        container_name: proxy
        build: 
            context: .
            dockerfile: Dockerfile.test.proxy
        ports:
            - "8080:8080"
    test-server:
        build:
            context: .
            dockerfile: Dockerfile.test.srv
        container_name: test_server
        restart: always
        ports:
            - "1337:1337"
